### PR TITLE
Directly depend on cheerio and formidable

### PR DESCRIPTION
**Pull request by rhansen**
Multiple commits:
* Directly depend on cheerio
* Directly depend on formidable

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Doesn't seem to be passing buddy, lemme know if you want me to take a look

**Comment by rhansen** [comment]
They're not passing on master either; the failures are not caused by this PR.

**Comment by JohnMcLear** [comment]
Fun....  Will look tomorrow :/

**Comment by JohnMcLear** [comment]
Confirmed 3 tests failing prior to tihs change.

**Pull request merged**
