### PR TITLE
add export setting

### PR DESCRIPTION
**Pull request by ilmartyrk**
As this HTML export seems broken and we at out project don't want to export HTML anyway I added a setting option to skip export. Default behaviour is exporting but if `settings.ep_comments_page.exportHTML = false;` export is skipped

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Which issue has broken export???

**Comment by JohnMcLear** [comment]
Also won't this fail if no settings for this plugin are set??

**Comment by ilmartyrk** [comment]
@JohnMcLear I don't see extra content getting exported on our app, but I haven't dug too deep. I only see the asterisks as link to comment, but don't see the comment paragraph, also tests didn't pass. It might be only my implementation fault and I might have some settings or smth. missing. Anyway I would still like to have option to skip out on export :)

**Comment by JohnMcLear** [comment]
Totally fine to have option but plz create issue with bug so we are aware about that too :)

**Comment by ilmartyrk** [comment]
@JohnMcLear I added the check `if (settings.ep_comments_page && settings.ep_comments_page.exportHtml === false) return;` so if no settings  are set nothing breaks.

**Comment by JohnMcLear** [comment]
Please as last step add backend test coverage.

One last thing to manually check is that if you have settings block but don't define this Boolean does it still export comments in html?

**Comment by ilmartyrk** [comment]
@JohnMcLear I tried to add test, but don't know how to add Settings into test. Tested manually and it works.

**Comment by ilmartyrk** [comment]
Should I make a test dependent on `settings.json` change so that it will by default skip, but will succeed if `exportHTML` setting is false and by doing this others will fail?

**Comment by JohnMcLear** [comment]
You can make settings be modified in real time as you run the test, for example: https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/webaccess.js#L22

**Comment by JohnMcLear** [comment]
Awesome thanks :)

One absolutely final thing, sorry!  Please include docs in README.md :)

**Comment by ilmartyrk** [comment]
@JohnMcLear updated README.md also fixed the export html tests

**Comment by JohnMcLear** [comment]
<3 :)

**Comment by JohnMcLear** [comment]
Awesome work thanks dude!

**Pull request merged**
