### PR TITLE
Create eu.json

### PR DESCRIPTION
**Pull request by izendegi**
Hi,

Here goes the translation to Basque (eu) of this plugin

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Hey @izendegi - translations are handled through translatewiki.net.  I will merge this but future changes and changes that will take precedent will be handled by @translatewiki and the team :)

**Comment by JohnMcLear** [comment]
Thanks!

**Comment by izendegi** [comment]
I'm sorry, I've helped translating Etherpad via @translatewiki but didn't find this plugin there, and that's why I ended doing this PR.

**Comment by JohnMcLear** [comment]
@izendegi ah, thanks twice then! :D  I'm pretty sure all core plugins that have translations should be setup there but I will let @translatewiki confirm :)

**Comment by Nikerabbit** [comment]
I am not sure why this isn't setup, but we'll add it.

**Pull request merged**
